# Cal3_S2

A `gtsam.Cal3_S2` represents a simple 5-parameter camera calibration model. This model is commonly used and includes parameters for focal lengths ($f_x, f_y$), skew ($s$), and the principal point ($u_0, v_0$). It does not model lens distortion. The calibration matrix $K$ is defined as:

$$
K = \begin{bmatrix} f_x & s & u_0 \\ 0 & f_y & v_0 \\ 0 & 0 & 1 \end{bmatrix}
$$

<a href="https://colab.research.google.com/github/borglab/gtsam/blob/develop/gtsam/geometry/doc/Cal3_S2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%pip install --quiet gtsam-develop

Note: you may need to restart the kernel to use updated packages.


In [2]:
import gtsam
import numpy as np
from gtsam import Cal3_S2, Point2

## Initialization

A `Cal3_S2` can be initialized in several ways. Initializing with no arguments yields a calibration model with the identity matrix as the calibration matrix. You can also construct a particular model with either individual values for the focal lengths, skew, and principle point, or pass all parameters in a 5-vector.

In [ ]:
# Default constructor: fx=1, fy=1, s=0, u0=0, v0=0
cal0 = Cal3_S2()
print("Default constructor (fx=1, fy=1, s=0, u0=0, v0=0):")
print(cal0)
print(f"fx: {cal0.fx()}, fy: {cal0.fy()}, s: {cal0.skew()}, u0: {cal0.px()}, v0: {cal0.py()}\n")

# From individual parameters: fx, fy, s, u0, v0
fx, fy, s, u0, v0 = 1500.0, 1600.0, 0.1, 320.0, 240.0
cal1 = Cal3_S2(fx, fy, s, u0, v0)
print("From parameters (fx, fy, s, u0, v0):")
print(cal1)
print(f"fx: {cal1.fx()}, fy: {cal1.fy()}, s: {cal1.skew()}, u0: {cal1.px()}, v0: {cal1.py()}\n")

# From a 5-vector [fx, fy, s, u0, v0]
cal_vector = np.array([1500.0, 1600.0, 0.1, 320.0, 240.0])
cal2 = Cal3_S2(cal_vector)
print("From a 5-vector [fx, fy, s, u0, v0]:")
print(cal2)
print(f"fx: {cal2.fx()}, fy: {cal2.fy()}, s: {cal2.skew()}, u0: {cal2.px()}, v0: {cal2.py()}\n")

Default constructor (fx=1, fy=1, s=0, u0=0, v0=0):
Cal3_S2[
	1, 0, 0;
	0, 1, 0;
	0, 0, 1
]

fx: 1.0, fy: 1.0, s: 0.0, u0: 0.0, v0: 0.0

From parameters (fx, fy, s, u0, v0):
Cal3_S2[
	1500, 0.1, 320;
	0, 1600, 240;
	0, 0, 1
]

fx: 1500.0, fy: 1600.0, s: 0.1, u0: 320.0, v0: 240.0

[320. 240.]
From a 5-vector [fx, fy, s, u0, v0]:
Cal3_S2[
	1500, 0.1, 320;
	0, 1600, 240;
	0, 0, 1
]

fx: 1500.0, fy: 1600.0, s: 0.1, u0: 320.0, v0: 240.0



Additionally, you can construct a calbration model with the field-of-view (FOV), in degrees, and the image width and height. The resulting model assumes zero skew and unit aspect (i.e. square pixel). The resulting calibration model is expected to have
$$u_0 = \frac{\text{width}}{2}, v_0 = \frac{\text{height}}{2}, s = 0$$
$$f_x=f_y=\frac{w}{2\cdot\tan\left(\frac{\text{FOV in radians}}{2}\right)}$$

In [17]:
# From FOV, width, and height
fov, w, h = 120, 100, 50
cal3 = Cal3_S2(fov, w, h)
print("From FOV (degrees) and image width and height:")
print(cal3)
print(f"fx: {cal3.fx()}, fy: {cal3.fy()}, s: {cal3.skew()}, u0: {cal3.px()}, v0: {cal3.py()}\n")

From FOV (degrees) and image width and height:
Cal3_S2[
	28.8675, 0, 50;
	0, 28.8675, 25;
	0, 0, 1
]

fx: 28.867513459481298, fy: 28.867513459481298, s: 0.0, u0: 50.0, v0: 25.0



## Properties

The model's properties can be access using the following member functions:
- `fx()`: Returns the focal length of the camera scaled by the pixel density along the x-axis.
- `fy()`: Returns the focal length of the camera scaled by the pixel density along the y-axis.
- `aspectRatio()`: Returns the aspect ratio computed with $f_x / f_y$.
- `skew()`: Returns the skew.
- `px()`: Returns the image center x-coordinate with respect to the image frame.
- `py()`: Returns the image center y-coordinate with respect to the image frame.
- `principlePoint()`: Returns a `numpy.ndarray` with 5 elements depicting a vectorized form of the calibration parameters. The return 5-vector follow the following form $\langle f_x, f_y, s, u_0, v_0 \rangle$.
- `K()`: Returns a `numpy.ndarray` with a $3\times 3$ shape representing the calibration matrix $K$ for the model.
- `inverse()`: Returns the inverted calibration matrix $K^{-1}$.

In [23]:
fx, fy, s, u0, v0 = 1500.0, 1600.0, 0.1, 320.0, 240.0
cal4 = Cal3_S2(fx, fy, s, u0, v0)

print("Calibration object call:")
print(f"fx: {cal4.fx()}")
print(f"fy: {cal4.fy()}")
print(f"s: {cal4.skew()}")
print(f"u0: {cal4.px()}")
print(f"v0: {cal4.py()}")
print(f"Principal point (u0, v0): {cal4.principalPoint()}")
print(f"Calibration vector [fx, fy, s, u0, v0]: {cal4.vector()}")
print(f"K matrix:\n{cal4.K()}")
print(f"inv(K) matrix:\n{cal4.inverse()}")

Calibration object call:
fx: 1500.0
fy: 1600.0
s: 0.1
u0: 320.0
v0: 240.0
Principal point (u0, v0): [320. 240.]
Calibration vector [fx, fy, s, u0, v0]: [1.5e+03 1.6e+03 1.0e-01 3.2e+02 2.4e+02]
K matrix:
[[1.5e+03 1.0e-01 3.2e+02]
 [0.0e+00 1.6e+03 2.4e+02]
 [0.0e+00 0.0e+00 1.0e+00]]
inv(K) matrix:
[[ 6.66666667e-04 -4.16666667e-08 -2.13323333e-01]
 [ 0.00000000e+00  6.25000000e-04 -1.50000000e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Basic Operations

### Calibration Operations

`Cal3_S2` provides methods to convert points between normalized image coordinates and pixel coordinates.

The `calibrate(p)` method converts a 2D point `p` from normalized image coordinates (where the image plane is at Z=1) to pixel coordinates. The formula is $p_{pixels} = K \cdot p_{normalized}$, where $p_{normalized}$ is a 2D point $(x,y)$ conceptually extended to homogeneous coordinates $(x,y,1)^T$ for matrix multiplication, and the result is then projected back to 2D pixel coordinates.

In [34]:
fx, fy, s, u0, v0 = 1500.0, 1600.0, 0.1, 320.0, 240.0
cal_model = Cal3_S2(fx, fy, s, u0, v0)

p_normalized = Point2(0.2, 0.3)
print(f"Normalized point p_n: {p_normalized}")

p_pixel = cal_model.calibrate(p_normalized)
print(f"Calibrated (pixel) point p_p: {p_pixel}")

Normalized point p_n: [0.2 0.3]
Calibrated (pixel) point p_p: [-0.21319001 -0.1498125 ]


The `uncalibrate(p)` method converts a 2D point `p` from pixel coordinates back to normalized image coordinates. This is the inverse operation of `calibrate()`. The formula is $p_{normalized} = K^{-1} \cdot p_{pixels}$.

In [35]:
p_n_recovered = cal_model.uncalibrate(p_pixel)
print(f"Pixel point p_p: {p_pixel}")
print(f"Uncalibrated (normalized) point p_n_recovered: {p_n_recovered}")

Pixel point p_p: [-0.21319001 -0.1498125 ]
Uncalibrated (normalized) point p_n_recovered: [0.2 0.3]


Both `calibrate` and `uncalibrate` can optionally compute Jacobians with respect to the calibration parameters (`Dcal`) and the input point (`Dp`). This is useful for optimization tasks. Note that matrices you pass in must be column-major arrays with the correct shape.

In [53]:
# Jacobians for calibrate(p_normalized)
Dcal_calibrate = np.zeros((2, 5), order='F')
Dp_calibrate = np.zeros((2, 2), order='F')
_ = cal_model.calibrate(p_normalized, Dcal_calibrate, Dp_calibrate) # Calibrated point is returned, assign to _
print(f"Jacobian Dcal_calibrate:\n{Dcal_calibrate}")
print(f"Jacobian Dp_calibrate:\n{Dp_calibrate}")

Jacobian Dcal_calibrate:
[[ 1.42126675e-04 -6.24218750e-09  9.98750000e-05 -6.66666667e-04
   4.16666667e-08]
 [ 0.00000000e+00  9.36328125e-05  0.00000000e+00  0.00000000e+00
  -6.25000000e-04]]
Jacobian Dp_calibrate:
[[ 6.66666667e-04 -4.16666667e-08]
 [ 0.00000000e+00  6.25000000e-04]]


### Manifold Operations

`Cal3_S2`, like many geometric types in GTSAM, is treated as a manifold. This means it supports operations like `retract` (moving on the manifold given a tangent vector) and `localCoordinates` (finding the tangent vector between two points on the manifold).

In [60]:
print("Original cal_model:")
print(cal_model)

# Retract: Apply a delta to the calibration parameters
delta_vec = np.array([10.0, 20.0, 0.05, 1.0, -1.0])
cal_retracted = cal_model.retract(delta_vec)
print(f"Delta vector: {delta_vec}")
print("Retracted cal_retracted:")
print(cal_retracted)

# Local coordinates: Find the delta between two calibrations
local_coords = cal_model.localCoordinates(cal_retracted)
print("\nLocal coordinates from cal_model to cal_retracted:")
print(local_coords)

Original cal_model:
Cal3_S2[
	1500, 0.1, 320;
	0, 1600, 240;
	0, 0, 1
]

Delta vector: [10.   20.    0.05  1.   -1.  ]
Retracted cal_retracted:
Cal3_S2[
	1510, 0.15, 321;
	0, 1620, 239;
	0, 0, 1
]


Local coordinates from cal_model to cal_retracted:
[10.   20.    0.05  1.   -1.  ]


### Other Utility Functions

In [62]:
cal_vector_for_eq = np.array([1500.0, 1600.0, 0.1, 320.0, 240.0])
cal_almost_eq_vector = np.array([1501.0, 1600.0, 0.1, 320.0, 240.0])

cal_eq = Cal3_S2(cal_vector_for_eq)
cal_diff = Cal3_S2(cal_almost_eq_vector)

print("cal_model:")
print(cal_model)
print("cal_eq:")
print(cal_eq)
print("cal_diff:")
print(cal_diff)

# Equals: Compare two Cal3_S2 objects with a tolerance
print(f"cal1 equals cal2? {cal_model.equals(cal_eq, 1e-9)}")
print(f"cal1 equals cal_different? {cal_model.equals(cal_diff, 1e-9)}")
print(f"cal1 equals cal_different with tol=1.5? {cal_model.equals(cal_diff, 1.5)}")

cal_model:
Cal3_S2[
	1500, 0.1, 320;
	0, 1600, 240;
	0, 0, 1
]

cal_eq:
Cal3_S2[
	1500, 0.1, 320;
	0, 1600, 240;
	0, 0, 1
]

cal_diff:
Cal3_S2[
	1501, 0.1, 320;
	0, 1600, 240;
	0, 0, 1
]

cal1 equals cal2? True
cal1 equals cal_different? False
cal1 equals cal_different with tol=1.5? True
